build:
    environment:
        php:
            version: 8.0.2
    dependencies:
        before:
            - find . -delete
            - git clone https://github.com/octobercms/october.git .
            - composer install --no-interaction --prefer-source
            - composer require vojtasvoboda/oc-twigextensions-plugin
    tests:
        override:
            -
                command: 'phpunit plugins/vojtasvoboda/twigextensions/tests --coverage-clover=coverage'
                coverage:
                    file: 'coverage'
                    format: 'php-clover'